import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Builds a landscape PDF table from pre-formatted headers and string rows
/// (same shape as CSV / report table).
Future<Uint8List> buildTransactionsReportPdf({
  required List<String> headers,
  required List<List<String>> dataRows,
  required String dateRangeLabel,
  required double totalRevenue,
  required int totalOrders,
}) async {
  final amountFmt = NumberFormat('#,##0.00', 'en_US');
  final generatedAt = DateFormat('MMM dd, yyyy – hh:mm a').format(DateTime.now());

  const primaryColor = PdfColor.fromInt(0xFF900B29);
  const headerBg = PdfColor.fromInt(0xFFF8F0F2);

  final doc = pw.Document(
    title: 'Transactions Report',
    author: 'Ahadu Merchant',
  );

  final n = headers.length;
  final columnWidths = <int, pw.TableColumnWidth>{
    for (var i = 0; i < n; i++) i: const pw.FlexColumnWidth(1),
  };
  final headerAlignments = <int, pw.Alignment>{
    for (var i = 0; i < n; i++) i: pw.Alignment.centerLeft,
  };
  final cellAlignments = <int, pw.Alignment>{
    for (var i = 0; i < n; i++) i: pw.Alignment.centerLeft,
  };

  doc.addPage(
    pw.MultiPage(
      /// Default is 20; large exports span many pages and hit [TooManyPagesException].
      maxPages: 2000,
      pageFormat: PdfPageFormat.a4.landscape,
      margin: const pw.EdgeInsets.all(28),
      header: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Ahadu Merchant',
                style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                  color: primaryColor,
                ),
              ),
              pw.Text(
                'Transactions Report',
                style: pw.TextStyle(
                  fontSize: 14,
                  color: PdfColors.grey700,
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 6),
          pw.Divider(color: primaryColor, thickness: 2),
          pw.SizedBox(height: 10),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Period: $dateRangeLabel',
                  style: const pw.TextStyle(fontSize: 10)),
              pw.Text('Generated: $generatedAt',
                  style: const pw.TextStyle(fontSize: 10)),
            ],
          ),
          pw.SizedBox(height: 6),
          pw.Row(
            children: [
              _summaryBox('Total Revenue', amountFmt.format(totalRevenue)),
              pw.SizedBox(width: 16),
              _summaryBox('Total Orders', totalOrders.toString()),
            ],
          ),
          pw.SizedBox(height: 12),
        ],
      ),
      footer: (context) => pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by Ahadu Merchant',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
          ),
        ],
      ),
      build: (context) => [
        pw.TableHelper.fromTextArray(
          context: context,
          headers: headers,
          data: dataRows,
          border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          headerStyle: pw.TextStyle(
            fontSize: 7,
            fontWeight: pw.FontWeight.bold,
            color: primaryColor,
          ),
          headerDecoration: const pw.BoxDecoration(color: headerBg),
          cellStyle: const pw.TextStyle(fontSize: 7),
          cellAlignment: pw.Alignment.centerLeft,
          cellPadding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 4),
          headerAlignments: headerAlignments,
          cellAlignments: cellAlignments,
          columnWidths: columnWidths,
        ),
      ],
    ),
  );

  return doc.save();
}

pw.Widget _summaryBox(String label, String value) {
  return pw.Container(
    padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
    decoration: pw.BoxDecoration(
      border: pw.Border.all(color: PdfColors.grey300),
      borderRadius: pw.BorderRadius.circular(4),
    ),
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label,
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
        pw.SizedBox(height: 2),
        pw.Text(value,
            style: pw.TextStyle(
                fontSize: 11, fontWeight: pw.FontWeight.bold)),
      ],
    ),
  );
}
