import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../domain/models/transaction.dart';

/// Builds a printable PDF receipt matching the detail screen fields (no currency symbol).
Future<Uint8List> buildTransactionReceiptPdf(Transaction t) async {
  final dateFmt = DateFormat('MMM dd, yyyy - hh:mm a');
  final amountFmt = NumberFormat('#,##0.00', 'en_US');

  final rows = <pw.Widget>[
    _pdfRow('Transaction ID', t.id),
    _pdfRow('Title', t.title),
    _pdfRow(
      t.enteredOn != null ? 'Entered on' : 'Date & time',
      dateFmt.format(t.date),
    ),
    _pdfRow('Type', _typeLabel(t)),
    _pdfRow('Status', t.status.toUpperCase()),
    _pdfRow('Net amount', '${t.amount >= 0 ? '+' : ''}${amountFmt.format(t.amount)}'),
  ];

  if (t.transactionValueDate != null) {
    rows.add(_pdfRow('Value date', dateFmt.format(t.transactionValueDate!)));
  }
  if (t.debitAmount != null) {
    rows.add(_pdfRow('Debit amount', amountFmt.format(t.debitAmount!)));
  }
  if (t.creditAmount != null) {
    rows.add(_pdfRow('Credit amount', amountFmt.format(t.creditAmount!)));
  }
  _addIf(rows, 'Debit account', t.debitAccount);
  _addIf(rows, 'Debit account name', t.debitAccountName);
  _addIf(rows, 'Credit account', t.creditAccount);
  _addIf(rows, 'Credit account name', t.creditAccountName);
  if (t.branchCode != null) {
    rows.add(_pdfRow('Branch code', t.branchCode.toString()));
  }
  if (t.batchNumber != null) {
    rows.add(_pdfRow('Batch number', t.batchNumber.toString()));
  }
  final n1 = t.narrativeDetail1;
  if (n1 != null && n1.trim().isNotEmpty && n1.trim() != t.title.trim()) {
    rows.add(_pdfRow('Narrative 1', n1));
  }
  _addIf(rows, 'Narrative 2', t.narrativeDetail2);
  _addIf(rows, 'Narrative 3', t.narrativeDetail3);

  final doc = pw.Document();
  doc.addPage(
    pw.MultiPage(
      pageTheme: const pw.PageTheme(
        margin: pw.EdgeInsets.all(40),
      ),
      build: (context) => [
        pw.Text(
          'Ahadu Merchant',
          style: pw.TextStyle(
            fontSize: 22,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey800,
          ),
        ),
        pw.SizedBox(height: 6),
        pw.Text(
          'Transaction receipt',
          style: pw.TextStyle(fontSize: 14, color: PdfColors.grey700),
        ),
        pw.SizedBox(height: 20),
        pw.Divider(thickness: 1),
        pw.SizedBox(height: 12),
        ...rows,
        pw.SizedBox(height: 24),
        pw.Text(
          'Generated by Ahadu Merchant',
          style: pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
        ),
      ],
    ),
  );

  return doc.save();
}

String _typeLabel(Transaction t) {
  final d = t.debitAmount ?? 0;
  final c = t.creditAmount ?? 0;
  if (t.debitAmount != null || t.creditAmount != null) {
    if (d > 0 && c == 0) return 'Debit';
    if (c > 0 && d == 0) return 'Credit';
  }
  return t.type == 'payment' ? 'Incoming Payment' : 'Outgoing Refund';
}

void _addIf(List<pw.Widget> rows, String label, String? value) {
  if (value != null && value.trim().isNotEmpty) {
    rows.add(_pdfRow(label, value));
  }
}

pw.Widget _pdfRow(String label, String value) {
  return pw.Padding(
    padding: const pw.EdgeInsets.only(bottom: 8),
    child: pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Expanded(
          flex: 2,
          child: pw.Text(label, style: const pw.TextStyle(fontSize: 10)),
        ),
        pw.Expanded(
          flex: 3,
          child: pw.Text(
            value,
            textAlign: pw.TextAlign.right,
            style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
          ),
        ),
      ],
    ),
  );
}
